### ISSUE TITLE
Responsible disclosure policy

### ISSUE THREAD

**Issue by JamieSlome** [aaronpk/Static-Maps-API-PHP#7]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@zer0yu) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by aaronpk** [comment]
Thanks, it looks like they already filed the issue a few days before this issue. I haven't maintained this project in about 8 years, and instead have switched to a different but related one, "Atlas", so I moved that issue over there to address it: https://github.com/aaronpk/Atlas/issues/8
